src/article/urls.py
from django.urls import path

from .views import *

app_name = 'article'

urlpatterns = [
    path('', list_posts, name='post_list'),
    path('detail/<slug:slug>/', detail_post, name='detail_post'),

    path('tag/<slug:tag_slug>/', tag_list, name='post_list_by_tag'),

    path('create/', create_post, name='create_post'),
    path('update/<int:pk>/', update_post, name='update_post'),
    path('delete/<int:pk>/', delete_post, name='delete_post'),

    path('category/<slug:category_slug>/', category_detail, name='category_detail'),
    path('create-category/', create_category, name='create_category'),
    path('update-category/<int:pk>/', update_category, name='update_category'),

    path('create-link/', create_link, name='create_link'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),

    path('summernote/', include('django_summernote.urls')),
    # path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns += i18n_patterns(
    path('', include('article.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('173e0222ccfb6c76e92fb8df9a19b645da151fa3d6b1d158262e26aa6bdff4ed/', views.user_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

src/article/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from taggit.managers import TaggableManager


class Post(models.Model):

    title = models.CharField(max_length=255, unique=True,  blank=True, null=True)
    slug = models.SlugField(max_length=250, unique=True, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    img = models.ImageField(upload_to="articles/images")
    in_trend = models.BooleanField(default=False, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    request_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='posts', verbose_name='category')

    categories_many = models.ManyToManyField('Category', related_name='many_posts', verbose_name='categories', blank=True, null=True)

    tags = TaggableManager()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title if self.title else "No title"

    def get_absolute_url(self):
        return reverse('article:detail_post', args=[str(self.slug)])

    class Meta:
        verbose_name = "article"
        verbose_name_plural = "articles"
        ordering = ['-created_at']


class Category(models.Model):

    title = models.CharField(max_length=255, unique=True, blank=True, null=True)
    slug = models.SlugField(max_length=250, unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title if self.title else "No title"

    def get_absolute_url(self):
        return reverse('article:category_detail', args=[str(self.slug)])

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"


class FriendlyLink(models.Model):
    friend = models.CharField(max_length=255, blank=True, null=True)
    name = models.CharField(max_length=255, unique=True, blank=True, null=True)
    link = models.URLField(max_length=128, db_index=True, unique=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('article:friend_detail', args=[str(self.friend), str(self.name), str(self.link)])

src/article/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from taggit.forms import TagWidget

from .models import Post, Category, FriendlyLink


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title_en', 'title_es', 'title_ar', 'content_en', 'content_es', 'content_ar', 'img', 'in_trend',
                  'is_active', 'tags', 'category', 'categories_many',)

        widgets = {
            'title_en': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'title En'}),
            'title_es': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'title Es'}),
            'title_ar': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'title Ar'}),
            'content_en': SummernoteWidget(),
            'content_es': SummernoteWidget(),
            'content_ar': SummernoteWidget(),
            'img': forms.FileInput(attrs={'class': 'form-file-input'}),
            'in_trend': forms.CheckboxInput(attrs={'class': 'form-checkbox'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-checkbox'}),
            'tags': TagWidget(attrs={'placeholder': 'Enter the tags separated by a space'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
            'categories_many': forms.SelectMultiple(attrs={'class': 'form-select'}),
        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title_en', 'title_es', 'title_ar',)

        widgets = {
            'title_en': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'title English'}),
            'title_es': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'title English'}),
            'title_ar': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'title English'}),
        }


class FriendlyLinkForm(forms.ModelForm):
    class Meta:
        model = FriendlyLink
        fields = ('friend', 'name_en', 'name_es', 'name_ar', 'link')

        widgets = {
            'friend': forms.TextInput(attrs={'class': 'form-input'}),
            'name_en': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'title English'}),
            'name_es': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'title English'}),
            'name_ar': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'title English'}),
            'link': forms.TextInput(attrs={'class': 'form-input'}),
        }

src/article/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Sum, Value
from django.db.models.functions import Coalesce

from django.shortcuts import render, get_object_or_404, redirect
from taggit.models import Tag

from article.forms import PostForm, CategoryForm, FriendlyLinkForm
from article.models import Post, Category, FriendlyLink

from django.contrib.auth.decorators import permission_required


# TODO: (get_common_data) ИСПОЛЬЗУЕТСЯ в create post, update post, create cat, update cat,  create link, update link

def get_common_data():
    all_categories = Category.objects.all()
    popular_posts = Post.objects.filter(is_active=True).order_by('-request_count')[:3]
    category_views = Category.objects.annotate(total_views=Coalesce(Sum('posts__request_count'), Value(0)))
    sorted_categories = sorted(category_views, key=lambda x: x.total_views, reverse=True)[:8]
    return {
        'all_categories': all_categories,
        'popular_posts': popular_posts,
        'category_views': category_views,
        'popular_categories': sorted_categories,
    }


def list_posts(request):
    current_url = request.path
    latest_post = Post.objects.order_by('-created_at').first()
    posts = Post.objects.all().order_by('-created_at').select_related('category')
    popular_posts = Post.objects.filter(is_active=True).order_by('-request_count')[:3]
    sidebar_posts = Post.objects.filter(in_trend=True)[:7]

    category_views = Category.objects.annotate(total_views=Coalesce(Sum('posts__request_count'), Value(0)))
    sorted_categories = sorted(category_views, key=lambda x: x.total_views, reverse=True)[:8]

    all_categories = Category.objects.all()

    paginator = Paginator(posts, 6)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'latest_post': latest_post,
        'posts': posts,
        'popular_posts': popular_posts,
        'sidebar_posts': sidebar_posts,
        'popular_categories': sorted_categories,
        'all_categories': all_categories,
        'current_url': current_url[1:],
    }

    return render(request, 'article/post/list.html', context)


def detail_post(request, slug):
    post = get_object_or_404(Post, slug=slug)

    viewed_post_cookie = request.COOKIES.get('viewed_post_{}'.format(post.id), False)

    if not viewed_post_cookie:
        post.request_count += 1
        post.save()

        popular_posts = Post.objects.filter(is_active=True).order_by('-request_count')[:3]
        friendly = FriendlyLink.objects.all()

        category_views = Category.objects.annotate(total_views=Coalesce(Sum('posts__request_count'), Value(0)))
        sorted_categories = sorted(category_views, key=lambda x: x.total_views, reverse=True)[:8]

        all_categories = Category.objects.all()

        many_categories = post.categories_many.all()

        context = {
            'post': post,
            'popular_posts': popular_posts,
            'friendly': friendly,
            'popular_categories': sorted_categories,
            'all_categories': all_categories,
            'many_categories': many_categories,
        }

        response = render(request, 'article/post/detail.html', context)
        response.set_cookie('viewed_post_{}'.format(post.id), True)
        return response

    popular_posts = Post.objects.filter(is_active=True).order_by('-request_count')[:3]
    friendly = FriendlyLink.objects.all()

    category_views = Category.objects.annotate(total_views=Coalesce(Sum('posts__request_count'), Value(0)))
    sorted_categories = sorted(category_views, key=lambda x: x.total_views, reverse=True)[:8]

    all_categories = Category.objects.all()

    many_categories = post.categories_many.all()

    context = {
        'post': post,
        'popular_posts': popular_posts,
        'friendly': friendly,
        'popular_categories': sorted_categories,
        'all_categories': all_categories,
        'many_categories': many_categories,
    }

    return render(request, 'article/post/detail.html', context)


# TODO: add post
@permission_required('article:create_post', raise_exception=True)
def create_post(request):
    form_of_post = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            owner = request.user

            new_post = form.save(commit=False)
            new_post.owner = owner
            new_post.save()

            form.save_m2m()

            return redirect('article:post_list')
    else:
        form_of_post = PostForm()

    common_data = get_common_data()

    context = {
        'form_of_post': form_of_post,
        'title': "Create post",
        **common_data
    }

    return render(request, "article/post/create_post.html", context)


# TODO: update post
@permission_required('article:update_post', raise_exception=True)
def update_post(request, pk):
    common_data = get_common_data()
    post = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('article:post_list')
        else:
            return render(request, 'article/post/update_post.html')
    else:
        form_of_post = PostForm(instance=post)
        context = {
            'title': "Update",
            'form_of_post': form_of_post,
            **common_data
        }
        return render(request, 'article/post/update_post.html', context)


# TODO: delete post

@permission_required('article:delete_post', raise_exception=True)
def delete_post(request, pk):
    post = Post.objects.get(id=pk)
    post.delete()
    return redirect('article:post_list')


# TODO: create Category
@permission_required('article:create_category', raise_exception=True)
def create_category(request):

    form_of_cat = CategoryForm()
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('article:post_list')
    else:
        form_of_cat = CategoryForm()

    common_data = get_common_data()

    context = {
        'form_of_cat': form_of_cat,
        'title': "Create category",
        **common_data
    }

    return render(request, "article/category/create_category.html", context)


# TODO: update category
@permission_required('article:update_post', raise_exception=True)
def update_category(request, pk):

    common_data = get_common_data()

    category = get_object_or_404(Category, id=pk)

    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('article:post_list')
        else:
            return render(request, 'article/post/update_post.html')
    else:
        form_of_cat = CategoryForm(instance=category)
        context = {
            'title': "Update category",
            'form_of_cat': form_of_cat,
            **common_data
        }
        return render(request, 'article/category/category_update.html', context)


# TODO: category detail
def category_detail(request, category_slug):
    current_url = request.path
    category = get_object_or_404(Category, slug=category_slug)
    initial_posts_1 = category.posts.all()
    initial_posts_2 = category.many_posts.all()
    initial_posts = initial_posts_1.union(initial_posts_2).order_by('-created_at')
    popular_posts = Post.objects.filter(is_active=True).order_by('-request_count')[:3]
    friendly = FriendlyLink.objects.all()

    category_views = Category.objects.annotate(total_views=Coalesce(Sum('posts__request_count'), Value(0)))
    sorted_categories = sorted(category_views, key=lambda x: x.total_views, reverse=True)[:8]

    all_categories = Category.objects.all()

    paginator = Paginator(initial_posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'category': category,
        'popular_posts': popular_posts,
        'posts': posts,
        'friendly': friendly,
        'popular_categories': sorted_categories,
        'all_categories': all_categories,
        'current_url': current_url,
    }

    return render(request, 'article/category/category_detail.html', context)


# TODO: create FriendlyLink
@permission_required('article:create_link', raise_exception=True)
def create_link(request):

    form_of_link = FriendlyLinkForm()
    if request.method == "POST":
        form = FriendlyLinkForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('article:post_list')
    else:
        form_of_link = FriendlyLinkForm()

    common_data = get_common_data()

    context = {
        'form_of_link': form_of_link,
        'title': "Create link",
        **common_data
    }

    return render(request, "article/friendlyLink/create_link.html", context)


# TODO: TAGS
def tag_list(request, tag_slug=None):
    post_list = Post.objects.all()
    popular_posts = Post.objects.filter(is_active=True).order_by('-request_count')[:3]
    friendly = FriendlyLink.objects.all()

    all_categories = Category.objects.all()
    category_views = Category.objects.annotate(total_views=Coalesce(Sum('posts__request_count'), Value(0)))
    sorted_categories = sorted(category_views, key=lambda x: x.total_views, reverse=True)[:8]

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:

src/article/templates/article/post/create_post.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    <div class="container">
        <div class="hint">
            <p class="hint_warning">Warning</p>
            <p class="hint_text">Но действия представителей оппозиции неоднозначны и будут преданы
                социально-демократической анафеме. В рамках
                спецификации современных стандартов, стремящиеся вытеснить традиционное производство, нанотехнологии
                набирают популярность среди определенных слоев населения, а значит, должны быть заблокированы в рамках
                своих
                собственных рациональных ограничений. Приятно, граждане, наблюдать, как независимые государства указаны
                как
                претенденты на роль ключевых факторов.</p>
        </div>

        <div class="add_post_wrap">

            <div class="add_post_form__wrap">
                <form action="" method="POST" class="add_post_form_container" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form_of_post.as_p }}
                    <button type="submit">Create</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

src/article/templates/article/post/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {{ post.title }}
    {% translate '| The Jet-Bet.IN Blog' %}
{% endblock %}

{% block content %}
    <main>

        <section>
            <div class="container">
                <div class="path">
                    <span><a href="{% url 'article:post_list' %}">{% translate 'Home' %}</a></span>

                    <svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><title/>
                        <path d="M202.1,450a15,15,0,0,1-10.6-25.61L365.79,250.1,191.5,75.81A15,15,0,0,1,212.71,54.6l184.9,184.9a15,15,0,0,1,0,21.21l-184.9,184.9A15,15,0,0,1,202.1,450Z"/>
                    </svg>

                    <span><a href="{{ post.category.get_absolute_url }}">{{ post.category.title }}</a></span>
                    <svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><title/>
                        <path d="M202.1,450a15,15,0,0,1-10.6-25.61L365.79,250.1,191.5,75.81A15,15,0,0,1,212.71,54.6l184.9,184.9a15,15,0,0,1,0,21.21l-184.9,184.9A15,15,0,0,1,202.1,450Z"/>
                    </svg>

                    <span>{{ post.title }}</span>
                </div>
                <div class="herro herro_detail">
                    <div class="herro_img">
                        <img src="{{ post.img.url }}" alt="">
                        <a href="{{ post.category.get_absolute_url }}"></a>
                    </div>
                    <div class="herro_description">

                        <div class="herro_sub-links">
                            {% for category in post.categories_many.all %}
                                <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
                            {% endfor %}
                        </div>

                        <h4 class="description_title">
                            {{ post.title }}
                        </h4>
                        <div class="herro_info">
                            <div class="herro_info-item date">
                                <span>{{ post.created_at|date:"F j, Y" }}</span>
                            </div>

                            <div class="herro_info-item">
                                <svg enable-background="new 0 0 32 32" id="Editable-line" version="1.1"
                                     viewBox="0 0 32 32" xml:space="preserve" xmlns="http://www.w3.org/2000/svg"
                                     xmlns:xlink="http://www.w3.org/1999/xlink">
                                    <path d="  M16,7C9.934,7,4.798,10.776,3,16c1.798,5.224,6.934,9,13,9s11.202-3.776,13-9C27.202,10.776,22.066,7,16,7z"
                                          fill="#fff" id="XMLID_10_" stroke="#fff" stroke-linecap="round"
                                          stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/>
                                    <circle cx="16" cy="16" fill="none" id="XMLID_12_" r="5" stroke="#000000"
                                            stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10"
                                            stroke-width="2"/>
                                </svg>
                                <span>{{ post.request_count }}</span>

                                {% if user.is_authenticated %}
                                    {% if user.is_staff %}
                                        <a href="{% url 'article:update_post' post.id %}" class="btn bg btn_detail">UPDATE
                                            POST</a>
                                        <a href="{% url 'article:delete_post' post.id %}"
                                           class="btn btn-danger btn_detail">DELETE</a>
                                    {% endif %}
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section>
            <div class="container">
                <div class="detal-descriptions">
                    <div class="descriptions">

                        {% include "article/post/includes/detail_social.html" %}

                        <div class="description">
                            <p>{{ post.content|safe }}</p>
                        </div>


                        {% if post.tags.all %}
                            <p class="tags">
                                Tags
                                {% for tag in post.tags.all %}
                                    <a href="{% url "article:post_list_by_tag" tag.slug %}">
                                        {{ tag.name }}
                                    </a>
                                    {% if not forloop.last %} {% endif %}
                                {% endfor %}
                            </p>
                        {% else %}
                        {% endif %}

                    </div>

{#                    <div class="detal-links">#}
{#                        <span>Friendly link</span>#}
{#                        <ul>#}
{#                            {% for friend in friendly %}#}
{#                                <li>#}
{#                                    <a href="{{ friend.link }}" target="_blank">{{ friend.name }}</a>#}
{#                                </li>#}
{#                            {% endfor %}#}
{#                        </ul>#}
{#                    </div>#}

                </div>
            </div>
        </section>

    </main>
{% endblock %}

src/article/templates/article/post/list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% translate 'The Jet-Bet.IN Blog |' %}

    {% for cat in all_categories %}
        {% if forloop.counter <= 5 %}
            {{ cat.title }},
        {% endif %}
    {% endfor %}

{% endblock %}

{% block content %}

    <main>
        <section>
            <div class="container">

                <div class="herro">

                    <div class="herro_publicity">

                        {% if latest_post.img %}
                            <div class="herro_img">
                                <a href="{{ latest_post.get_absolute_url }}">
                                    <img src="{{ latest_post.img.url }}" class="img-fluid" alt="img">
                                </a>
                            </div>

                            <div class="herro_publicity-links">
                                <div class="herro_sub-link">
                                    <div>
                                        <p>{{ latest_post.category.title }}</p>
                                        <a href="{{ latest_post.category.get_absolute_url }}"></a>
                                    </div>
                                </div>
                                <a class="main-link" href="{{ latest_post.get_absolute_url }}">
                                    <h1>{{ latest_post.title }}</h1>
                                </a>
                            </div>
                        {% endif %}
                    </div>

                    <div class="herro_links">
                        <div class="herro_links-title">
                            <h4>{% translate 'Trending' %}</h4>
                        </div>
                        <ul>
                            {% for post in sidebar_posts %}
                                <li>
                                    <a href="{{ post.get_absolute_url }}">{{ post.title|truncatewords:12 }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

                </div>

            </div>
        </section>

        <section class="latest">
            <div class="container">

                <div class="latest-title">
                    <h4>{% translate 'LATEST POSTS' %}</h4>
                </div>

                <div class="latest-items">
                    {% for post in posts %}
                        {% if post.img %}
                            <div class="latest_publicity">
                                <div class="latest_img">
                                    <img src="{{ post.img.url }}" alt="{{ post.title }}">
                                    <a href="{{ post.get_absolute_url }}"></a>
                                </div>

                                <div class="latest_publicity-links">
                                    <div class="latest_sub-link">
                                        <div>
                                            <p>{{ post.category.title }}</p>
                                            <a href="{{ post.category.get_absolute_url }}"></a>
                                        </div>
                                    </div>
                                    <a class="main-link" href="{{ post.get_absolute_url }}">
                                        {{ post.title|truncatechars:30 }}
                                    </a>

                                    <h4>
                                        {{ post.content|truncatewords:60|safe }}
                                    </h4>

                                    <span>{{ post.created_at|date:"F j, Y" }}</span>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </section>

    </main>
        {% include "article/post/includes/pagination.html" with page=posts %}

{% endblock %}

src/article/templates/article/post/post_tags.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} {{ tag }} {% translate '| The Jet-Bet.IN Blog' %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="detail_image_top">
            <a href="{% url 'article:post_list' %}">{% translate 'Home' %}</a>
            <span class="separator"> > </span>
            <span>Tags</span>
            <span class="separator"> > </span>
            <span>{{ tag.name }}</span>
        </div>

        {% if tag %}
            <p class="tags_title"> Tag: {{ tag.name }}</p>
        {% endif %}

        <div class="detal-descriptions">

            <div class="detal-news">
                {% for post in posts %}
                    <div class="detal-news_item">

                        <div class="detal-news_img">
                            <a href="{{ post.get_absolute_url }}"><img src="{{ post.img.url }}" alt=""></a>
                        </div>

                        <div class="detal-news-description">
                            <a href="{{ post.get_absolute_url }}">{{ post.title|truncatewords:10 }}</a>
{#                            <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>#}
                            <p>
                                {{ post.content|truncatewords:30|safe }}
                            </p>
                            <p>
                                <span>{{ post.created_at|date:"F j, Y" }}</span>
                            </p>
                            <a class="button-type" href="{{ post.get_absolute_url }}">Read more</a>
                        </div>
                    </div>
                {% endfor %}
                {% if posts %}
                    {% include "article/post/includes/pagination.html" with page=posts %}
                {% endif %}
            </div>

            {#        <div class="detal-links">#}
            {#            <span>{% translate 'Friendly link' %}</span>#}
            {#            <ul>#}
            {#                {% for link in friendly %}#}
            {#                    <li>#}
            {#                        <a href="{{ link.link }}" target="_blank">{{ link.name }}</a>#}
            {#                    </li>#}
            {#                {% endfor %}#}
            {#            </ul>#}
            {#        </div>#}

        </div>

    </div>
{% endblock %}

src/article/templates/article/post/update_post.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}
{{ form.media }}
{% block content %}

    <div class="container">
        <div class="hint">
            <p class="hint_warning">Warning</p>
            <p class="hint_text">Но действия представителей оппозиции неоднозначны и будут преданы
                социально-демократической
                анафеме. В рамках
                спецификации современных стандартов, стремящиеся вытеснить традиционное производство, нанотехнологии
                набирают популярность среди определенных слоев населения, а значит, должны быть заблокированы в рамках
                своих
                собственных рациональных ограничений. Приятно, граждане, наблюдать, как независимые государства указаны
                как
                претенденты на роль ключевых факторов.</p>
        </div>

        <div class="add_post_wrap">
            <div class="add_post_form__wrap">
                <form action="" method="POST" class="add_post_form_container" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form_of_post.as_p }}
                    <button type="submit">Update</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}